In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

### №6

In [6]:
fx = fy = 400
cx = 960
cy = 540

angle = np.pi / 4
r = R.from_rotvec([0, 0, angle]).as_matrix()
t = np.array([0, 0, 10])

K = np.array([[fx, 0, cx],
              [0, fy, cy],
              [0, 0, 1]])

P = K @ np.hstack((r, t.reshape(3, 1)))
X = np.array([10, -10, 100, 1])

x = P @ X
x /= x[2]

print("p:")
print(P)
print("x:", x[:2].astype(int))

p:
[[ 2.82842712e+02 -2.82842712e+02  9.60000000e+02  9.60000000e+03]
 [ 2.82842712e+02  2.82842712e+02  5.40000000e+02  5.40000000e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+01]]
x: [1011  540]


### №13

In [30]:
angle = np.pi / 4
r = R.from_rotvec([0, 0, angle]).as_matrix()
t = np.array([10, 0, 0])

F = np.cross(t, r, axisa=0, axisb=0, axisc=0)

print(F)

[[  0.           0.           0.        ]
 [  0.          -0.         -10.        ]
 [  7.07106781   7.07106781   0.        ]]


### №14

$ \left(
\begin{matrix} 
x_2 \\
y_2 \\
z_2 
\end{matrix} 
\right) =
R_2^{-1} \left[ \left(
\begin{matrix} 
x_1 \\
y_1 \\
z_1 
\end{matrix} 
\right) - T \right] $

In [9]:
angle = np.pi / 4
R1 = R.from_rotvec([0, 0, angle]).as_matrix()
R2 = R.from_rotvec([0, - angle, 0]).as_matrix()
R2_inv = np.linalg.inv(R2)
T = np.array([-10, 0, 0])

F = np.cross(T, R2_inv @ R1, axisa=0, axisb=0, axisc=0)

print(F)

[[-0.          0.          0.        ]
 [-5.          5.          7.07106781]
 [-7.07106781 -7.07106781 -0.        ]]


### №15

In [11]:
u, s, vh = np.linalg.svd(F) 

e1 = vh[np.isclose(s, np.zeros(s.shape))][0]
e1 /= e1[2]
e2 = T
print("e1: ", e1)
print("e2: ", e2)
# print(e2 @ F @ e1)

e1:  [ 0.70710678 -0.70710678  1.        ]
e2:  [-10   0   0]


Эпиполь второго изображения находится на бесконечности.
$ F \cdot e_1 = 0, \quad e_2 = K_2 \cdot T_2. $

### №16

In [27]:
q = np.array([0, 0, 1])

l1 = F.T @ q.T
l2 = F @ q.T

print(f"l: {l1[0]}*x + {l1[1]}*y + {l1[2]} = 0")
print(f"l': {l2[0]}*x' + {l2[1]}*y' + {l2[2]} = 0")

l: -7.0710678118654755*x + -7.071067811865475*y + 0.0 = 0
l': 0.0*x' + 7.071067811865475*y' + 0.0 = 0


$ l_1 = F^T \cdot q \quad l_2 = F \cdot q. $