In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=3, floatmode='fixed')

### №1

In [3]:
A = np.array([[0.5, 2.16506351, 0.4330127],
              [-0.8660254, 1.25, 0.25],
              [0, 0.5, 2.5]])

u, s, vh = np.linalg.svd(A)
    
R = u @ vh

print(f"R: \n{R}")
print("angle =", np.rint(np.arccos(R[1,1]) * 180 / np.pi))

R: 
[[ 5.000e-01  8.660e-01 -3.880e-10]
 [-8.660e-01  5.000e-01  1.655e-11]
 [ 2.083e-10  3.277e-10  1.000e+00]]
angle = 60.0


By the element $R[1,0]$ and by the fact that $\cos{(60)}=\frac{1}{2}$ it is clear that this is a negative angle, that is, $R (-\theta)$ $\Rightarrow$ this is a clockwise rotation relative to the $z$ coordinate, that is $R_{z}(-\theta), $ where $\theta = 60.$


### №2

In [4]:
n = 3
a = np.ones((n, n))

for i in range(1, n + 1):
    for j in range(1, n + 1):
        a[i-1][j-1] /= (i + j - 1)

u, s, vh = np.linalg.svd(a)

for i in range(s.shape[0]):
    s[i] = 1 / s[i]
    
a_pri = vh.T @ np.diag(s).T @ u.T

print(a_pri)

[[   9.000  -36.000   30.000]
 [ -36.000  192.000 -180.000]
 [  30.000 -180.000  180.000]]


In [5]:
n = 10
a = np.ones((n, n))

for i in range(1, n + 1):
    for j in range(1, n + 1):
        a[i-1][j-1] /= (i + j - 1)
        
u, s, vh = np.linalg.svd(a)

for i in range(s.shape[0]):
    s[i] = 1 / s[i]
    
a_pri = vh.T @ np.diag(s).T @ u.T

print(a_pri)

[[ 1.000e+02 -4.950e+03  7.919e+04 -6.005e+05  2.522e+06 -6.306e+06
   9.608e+06 -8.751e+06  4.375e+06 -9.237e+05]
 [-4.950e+03  3.267e+05 -5.880e+06  4.756e+07 -2.081e+08  5.351e+08
  -8.323e+08  7.700e+08 -3.898e+08  8.313e+07]
 [ 7.919e+04 -5.880e+06  1.129e+08 -9.513e+08  4.281e+09 -1.124e+10
   1.776e+10 -1.663e+10  8.505e+09 -1.829e+09]
 [-6.005e+05  4.756e+07 -9.513e+08  8.244e+09 -3.787e+10  1.010e+11
  -1.616e+11  1.529e+11 -7.883e+10  1.707e+10]
 [ 2.522e+06 -2.081e+08  4.281e+09 -3.787e+10  1.767e+11 -4.772e+11
   7.712e+11 -7.358e+11  3.820e+11 -8.321e+10]
 [-6.306e+06  5.351e+08 -1.124e+10  1.010e+11 -4.772e+11  1.301e+12
  -2.121e+12  2.038e+12 -1.064e+12  2.330e+11]
 [ 9.608e+06 -8.323e+08  1.776e+10 -1.616e+11  7.712e+11 -2.121e+12
   3.480e+12 -3.364e+12  1.766e+12 -3.883e+11]
 [-8.751e+06  7.700e+08 -1.663e+10  1.529e+11 -7.358e+11  2.038e+12
  -3.364e+12  3.267e+12 -1.723e+12  3.804e+11]
 [ 4.375e+06 -3.898e+08  8.506e+09 -7.883e+10  3.820e+11 -1.064e+12
   1.766e+12

### №3

In [6]:
n = 4
A = np.empty([n, n])
for i in range(n):
    for j in range(n):
        A[i][j] = i + j - 1

#print(A, " rank(A):", np.linalg.matrix_rank(A))

u, s, v = np.linalg.svd(A)
nulls = np.zeros(s.shape)

x_1 = v[np.isclose(s, nulls)][0]
x_2 = v[np.isclose(s, nulls)][1]

#so rank(A) = 2, hence 2 close to zero singular values


'''
print(x_1.T @ x_1)
print(x_2.T @ x_2)

b_1 = A @ x_1
b_2 = A @ x_2

print(b_1)
print(b_2)
'''

print(x_1)
print(x_2)

[ 0.347 -0.147 -0.747  0.547]
[-0.424  0.824 -0.376 -0.024]


### №4

In [7]:
from random import randint


def vect_prod(a,b):
    return np.asarray([a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-b[0]*a[1]], dtype='f')

a, b, c, d, e = [randint(-10, 10) for i in range(5)]
l1 = [a, b, c]
l2 = [c, d, e]

print("l1:", l1, "  l2:", l2)

a = vect_prod(l1, l2)
a_len = a.shape[0]

#assert a[a_len-1] != 0, "straight lines don't intersect or not a straight line was generated"

if a[a_len-1] != 0:
    for i in range(a_len):
        a[i] /= a[a_len-1]
        
    a = a[:2]
    print("2D coordinates of the intersection point:", a)
else:
    print("Homogeneous coordinates of a 2D intersection point", a)

l1: [-2, 9, 3]   l2: [3, -4, 9]
2D coordinates of the intersection point: [-4.895 -1.421]


### №5


Пусть $A \in \mathbb R^{n \times n} $ действительная матрица и $\operatorname{rank}{(A)} = k.$ Также пусть $ A = U \Sigma V^{\top} $— сингулярное разложение матрицы $ A $ с сингулярными числами $ \sigma_1 \geq \sigma_2 \geq \ldots \geq \sigma_k > 0. $ Пусть $ A_{r}=\sum\limits_{i = 1}^r \sigma_i u_i v_i^{\top}, $ тогда 
$$ \operatorname{{\underset{\operatorname{rank}(B)=r}{min}}} \left\| A - B \right\|_F^2 = \left\| A - A_r \right\|_F^2 = \sum\limits_{i = r+ 1}^k \sigma_i^2. $$
__Доказательство:__ $$ \Bigg\|{ A - A_r } \Bigg\|_F^2 = \bigg\| \sum\limits_{i = 1}^k \sigma_i u_i v_i^{\top} - \sum\limits_{i = 1}^r \sigma_i u_i v_i^{\top} \bigg\|_F^2 = \left\| \sum\limits_{i = r+ 1}^k \sigma_i u_i v_i^{\top} \right\|_F^2 = \left\| U \operatorname{diag}(0, \ldots, 0, \sigma_{r+1}, \ldots, \sigma_k) V^{\top} \right\|_F^2 = \sum\limits_{i = r+ 1}^k \sigma_i^2. $$

Покажем, что если найдется любая другая матрица $ C_r = XY^{\top} $ где $ X $ и $ Y $ имеют $ r $ столбцов, то

$$ \left\| A - A_r \right\|_F^2 = \sum_{i = r + 1}^n \sigma_i^2 \leq \left\|A - C_r \right\|_F^2. $$

По неравенству треугольника, если $ A = A_1 + A_2, $ то $ \sigma_1(A) \leq \sigma_1(A_1) + \sigma_1(A_2). $ Соответственно $ A_{1, k} $ и $ A_{2, k} $ имеют $ k $ ранг приближения к матрицам $ A_1 $ и $ A_2. $ Тогда $ ∀ i,j \geq 1: $

$$ \sigma_i (A_1) + \sigma_j (A_2) = \sigma_1 (A_1 - A_{1, i-1}) + \sigma_1(A_2 - A_{2, j-1}). \tag{1} $$

$$ if A_1 = 
\left(
\begin{matrix} 
3 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 1 
\end{matrix} 
\right) \Rightarrow  A_1 - A_{1, 1} =   
\left(
\begin{matrix}
3 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 1 
\end{matrix}
\right) - 
\left(
\begin{matrix}
3 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{matrix}
\right) = 
\left(
\begin{matrix}
0 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 1 
\end{matrix}
\right) \Rightarrow \sigma_1(A_1) = \sigma_1 (A_1 - A_{1, 1}) = 2, \quad \mbox{at} \quad i = 2.
$$


Далее по неравенству треугольника равенство $(1)$ оценим снизу:
$$ \sigma_1 (A_1 - A_{1, i-1}) + \sigma_1(A_2 - A_{2, j-1}) \geq \sigma_1(A - A_{1, i-1} - A_{2, j-1}), \quad \mbox{где} \quad A = A_1 + A_2.$$
$$ \sigma_1(A - A_{1, i-1} - A_{2, j-1}) \geq \sigma_1(A - A_{i+j-2}) =\sigma _{i+j-1}(A). $$
Последнее неравенство справедливо, поскольку ранг суммы $ A_{1, i-1} + A_{2,j-1} $ не превосходит ранг матрицы $ A_{i+j-2}. $ 

Если положить $ A_1 = A - C_r $ и $ A_2 = C_r, $ то из-за того, что $ \sigma_{r+1}(C_r) = 0 \Rightarrow \forall i \geq 1 \cap j=r+1: \sigma_{i}(A - C_r) \geq \sigma_{r+i}(A). $

Тогда $ \left\| A - A_r \right\|_F^2 = \sum\limits_{i=r+1}^n \sigma_i(A)^2 \leq \sum\limits_{i=1}^n \sigma_i(A - C_r)^2 = \left\| A - C_r \right\|_F^2. $

То есть любое другое приближение матрицы $ A $ матрицей $ C_r $ либо равно, либо больше, чем приближение, обеспечиваемое матрицей $ A_r. $ Cледовательно, матрица $A_r$— ближайшая матрица (в смысле нормы Фробениуса) к матрице $A.$

### №7

http://www.dspa.ru/articles/year2017/jour17_3/art17_3_3.pdf

And I also found a misprint in this article that when they form the matrix _A_, the matrix _O_ is of the wrong dimension. For everything to match, you need a 4x3 dimension and not like their 3x3.

In [8]:
def point_pair_generator(H_0, n = 4):
    lst1 = []
    lst1.extend([[randint(-10, 10), randint(-10, 10)] for i in range(n)])
    lst2 = np.zeros((n, 3))
    
    for i in range(n):
        lst1[i] = np.append(lst1[i], 1)
        lst2[i] = (H_0 @ lst1[i])
        assert lst2[i][2] != 0
        lst2[i] /= lst2[i][2]

    lst1 = np.asarray(lst1)
    #print(lst1)
    #print(lst2)
    return lst1, lst2

In [9]:
def find_homography_matrix(lst1, lst2):
    A = np.zeros((8, 8), dtype='f')
    A[:4,:3] = lst1
    A[4:,3:6] = lst1
    A[:4, 6:8] = [[-i[0] * j[0], - j[0] * i[1]] for i, j in zip(lst1, lst2)]
    A[4:, 6:8] = [[-i[0] * j[1], - j[1] * i[1]] for i, j in zip(lst1, lst2)]
    #print(A)
    B = np.zeros(8, dtype='f')
    B[:4] = lst2[:, 0]
    B[4:8] = lst2[:, 1]
    #print(B)
    u, s, vh = np.linalg.svd(A)
    for i in range(s.shape[0]):
        s[i] = 1 / s[i]
    H_pri = vh.T @ np.diag(s).T @ u.T @ B
    H_pri = np.append(H_pri, 1)
    H = H_pri.reshape(-1, 3)
    return H

In [10]:
H_0 = np.array([[0.5, 2.16506351, 0.4330127],
              [-0.8660254, 1.25, 0.25],
              [0, 0.5, 1]])
print(f"H_0: \n{H_0}")
print(f"H: \n{find_homography_matrix(*point_pair_generator(H_0))}")

H_0: 
[[ 0.500  2.165  0.433]
 [-0.866  1.250  0.250]
 [ 0.000  0.500  1.000]]
H: 
[[ 5.000e-01  2.165e+00  4.330e-01]
 [-8.660e-01  1.250e+00  2.500e-01]
 [-7.451e-09  5.000e-01  1.000e+00]]


### №9

But the matrix of internal parameters of the camera is not given.
And of course the homography matrix 
$H = K R K^{-1}, $ where $R$ — rotation matrix around the x-axis by 30 degrees, and $K$ is the matrix of internal parameters of both cameras.

In [11]:
theta = np.pi / 6
R = np.array([[1, 0, 0],
              [0, np.cos(theta), - np.sin(theta)],
              [0, np.sin(theta), np.cos(theta)]])

f_x = 1
f_y = 1
c_x = 1
c_y = 2

K = np.array([[f_x, 0, c_x], 
              [0, f_y, c_y],
              [0, 0, 1]])

H = K @ R @ np.linalg.inv(K)
print(H)

[[ 1.000  0.500 -1.134]
 [ 0.000  1.866 -2.500]
 [ 0.000  0.500 -0.134]]
